apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - shopease-frontend-prod-sealedsecret.yaml

namespace: shopease-prod

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
